# -*- coding: utf-8 -*-
"""Krebsville_Nights_Controller.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mly9SWFeeBwS9f-g1oKapvMsGfUDUWVz
"""

import random
import json

character = {
    "name": "Dr. Grant",
    "time_tokens": 50,         # Reset for Zone 0
    "credits": 1000,           # Reset for Zone 0
    "hazard_level": 0,         # Reset for Zone 0
    "companion": "Nurse Carter",
    "inventory": [],           # Starting empty
    "modifiers": {
        "tech": 5,             # Original high-tier stats [cite: 20]
        "stealth": 3,          # [cite: 22]
        "reflexes": 2          # [cite: 24]
    }
}

import random

# --- DR. GRANT'S CHARACTER SHEET ---
character = {
    "name": "Dr. Grant",
    "time_tokens": 37,
    "credits": 3480,
    "hazard_level": 4,
    "companion": "Nurse Carter",
    "modifiers": {
        "tech": 5,
        "stealth": 3,
        "reflexes": 2
    }
}

def roll_check(stat_name):
    modifier = character['modifiers'].get(stat_name, 0)
    die_roll = random.randint(1, 20)
    total = die_roll + modifier
    print(f"🎲 ROLL: {die_roll} + {modifier} ({stat_name.upper()})")
    print(f"📊 TOTAL: {total}")
    return total

# Example usage:
# roll_check("tech")

def save_progress():
    with open("game_save.txt", "w") as f:
        f.write(str(character))
    print("ኂ2 Game State Saved to Colab disk.")

def load_progress():
    global character
    try:
        with open("game_save.txt", "r") as f:
            character = eval(f.read())
        print("ኁ43 Progress Loaded Successfully.")
    except FileNotFoundError:
        print("❌ No save file found.")

# Defining a local version of show_dashboard to prevent the NameError
def show_dashboard(scene_key=None):
    print("="*40)
    print(f"ኂ05 LOCATION: {character.get('location', 'ZONE 2')}")
    print(f"⌛ TIME: {character['time_tokens']} | ኁ76 CREDITS: {character['credits']}")
    print(f"⚠️ HAZARD: {character['hazard_level']}/5")
    print("="*40)

# Now we can safely call it
show_dashboard()

def show_dashboard():
    print("="*40)
    print(f"📍 LOCATION: ZONE 2 - GENETIC SEQUENCING HUB")
    print(f"⏳ TIME TOKENS: {character['time_tokens']} | 💰 CREDITS: {character['credits']}")
    print(f"⚠️ HAZARD LEVEL: {character['hazard_level']}/5")
    print(f"👥 COMPANION: {character['companion']}")
    print("="*40)

show_dashboard()

def engage_combat(enemy_name, enemy_difficulty):
    print(f"⚔️ ENGAGING: {enemy_name} (Danger Level: {enemy_difficulty})")

    # We use Reflexes to see who acts first
    initiative = roll_check("reflexes")

    if initiative >= 12:
        print("⚡ Dr. Grant acts first!")
        # Use Tech for sabotage or Reflexes for a physical strike
        attack = roll_check("tech")

        if attack >= enemy_difficulty:
            print(f"✅ SUCCESS: {enemy_name} neutralized/bypassed.")
            return True
        else:
            print(f"❌ MISS: {enemy_name} counters!")

    # If initiative fails or attack misses, Dr. Grant takes damage
    print(f"💥 DAMAGE SUSTAINED: -2 Time Tokens")
    character['time_tokens'] -= 2
    show_dashboard()
    return False

# Example usage for tomorrow:
# engage_combat("Maintenance Drone 05", 15)

def generate_loot(is_elite_vault=False):
    print("🔍 SEARCHING AREA...")

    # Random credit find
    found_credits = random.randint(50, 200)
    if is_elite_vault:
        found_credits *= 2 # Double loot for high-risk areas

    character['credits'] += found_credits

    # Random Item Table
    items = [
        "Empty Syringe", "Decrypted Patient File", "Broken Circuit Board",
        "Adrenaline Shot (+2 Reflexes next roll)", "Data Spike (Auto-pass one Tech check)",
        "Coolant Spray (Ignore Thermal Sensors once)", "Elite Keycard Fragment"
    ]

    found_item = random.choice(items)

    print("-" * 30)
    print(f"💰 FOUND: {found_credits} Credits")
    print(f"📦 ITEM: {found_item}")
    print("-" * 30)

    show_dashboard()

# Usage for tomorrow:
# generate_loot(is_elite_vault=True)

def get_sync_payload():
    """Generates a formatted status report to paste into Poe/OpenAI."""
    status = "⚠️ HAZARD CRITICAL" if character['hazard_level'] >= 4 else "✅ SYSTEM STABLE"

    payload = f"""
--- 🛰️ DATA SYNC: {character['name'].upper()} ---
STATUS: {status}
LOCATION: Zone 2 - Sequencing Hub Vents
------------------------------------------
⏳ TIME TOKENS: {character['time_tokens']}
💰 ARP CREDITS: {character['credits']}
☣️ HAZARD LEVEL: {character['hazard_level']}
🎒 INVENTORY: {", ".join(character['inventory']) if character['inventory'] else "Empty"}
------------------------------------------
[SYSTEM PROMPT]: Dr. Grant is currently in a Level {character['hazard_level']} hazard zone.
The screen is {"GLITCHING" if character['hazard_level'] >= 4 else "STABLE"}.
Describe the tension in the room and the next environmental obstacle.
--- END SYNC ---
"""
    print(payload)

# To use it, just run:
# get_sync_payload()

import os

file_path = '/content/KrebsvillePoeOpenAIColabREADME.md'

if os.path.exists(file_path):
    with open(file_path, 'r') as f:
        print(f.read())
else:
    print(f"❌ Error: The file '{file_path}' was not found.")
    print("💡 Hint: Check the file sidebar on the left. If you meant the default README, it is located at: /content/sample_data/README.md")

import time

def run_system_diagnostic():
    print("📋 INITIALIZING KREBSVILLE NIGHTS SYSTEM CHECK...")
    print("-" * 40)

    # 1. Check Sentry (The Sensors)
    try:
        log_game_event("system", "Running pre-flight diagnostic")
        print("✅ [SENTRY] Sensors Online. Breadcrumbs tracking active.")
    except Exception:
        print("❌ [SENTRY] Sensors Offline. Check your DSN.")

    # 2. Check Neon (The Time Machine)
    try:
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()
        cur.execute("SELECT 1")
        cur.close()
        conn.close()
        print("✅ [NEON] Database Linked. Quick-Saves available.")
    except Exception:
        print("❌ [NEON] Connection Failed. Timeline is unstable.")

    # 3. Check Supabase (The HUD)
    try:
        # A simple ping to the game_sessions table
        supabase.table("game_sessions").select("id").limit(1).execute()
        print("✅ [SUPABASE] Realtime HUD Sync active.")
    except Exception:
        print("❌ [SUPABASE] HUD Link severed. Replit may not update.")

    print("-" * 40)
    print("READY FOR COMMAND TIER BREACH. GOOD LUCK, DOCTOR.")

# === EXECUTION ===
# run_system_diagnostic()

# === NEON CONFIGURATION ===
NEON_API_KEY = "napi_2jddte64vz67m0fo0u3urq50uc3rmnv62no6qtwlwbhl7lkktvgn89pkqxn22n2k"      # From User Settings -> API Keys
PROJECT_ID = "soft-block-40378950"       # From the URL or Project Dashboard
PARENT_BRANCH_ID = "main"   # Usually 'main' unless you're deep in a sub-timeline

# This is the connection string for your ACTIVE branch
DATABASE_URL = "postgresql://..."

def carter_heal():
    if character['credits'] >= 100:
        print("💉 Nurse Carter uses a stim-pack.")
        character['time_tokens'] += 5
        character['credits'] -= 100
        print("📈 +5 Time Tokens restored.")
    else:
        print("❌ Not enough Credits for medical supplies!")
    show_dashboard()

import json

def export_character():
    with open('dr_grant_save.json', 'w') as f:
        json.dump(character, f)
    print("✅ Full Character State Exported to 'dr_grant_save.json'.")
    print("Download this file from the left sidebar if you want a permanent backup!")

export_character()

from IPython.display import Image, display, HTML

def show_scene(image_url, caption=""):
    display(HTML(f"""
    <div style="border: 2px solid #a855f7; padding: 10px; background-color: #020205; width: 600px; text-align: center;">
        <img src="{image_url}" width="600" style="border: 1px solid #444;">
        <p style="color: #a855f7; font-family: 'Courier New'; margin-top: 10px; font-weight: bold;">{caption.upper()}</p>
    </div>
    """))

# Database of your URLs
assets = {
    "nurse_carter": "http://googleusercontent.com/image_generation_content/5",
    "zone_2_lab": "http://googleusercontent.com/image_generation_content/15",
    "maintenance_drone": "http://googleusercontent.com/image_generation_content/12"
}

def show_dashboard(scene_key=None):
    if scene_key and scene_key in assets:
        show_scene(assets[scene_key], f"Current Location: {scene_key.replace('_', ' ')}")

    print("="*60)
    print(f"⌛ TIME: {character['time_tokens']} | ኁ76 CREDITS: {character['credits']} | ⚠️ HAZARD: {character['hazard_level']}")
    print(f"👥 COMPANION: {character['companion']}")
    print("="*60)

# Now that show_scene is defined, this will work:
show_dashboard("zone_2_lab")

import random

def er_vitals_override(tech_mod=5):
    """
    ER Vitals Override Mini-game
    Run this every 3 turns to maintain bio-signature masking.
    """
    print("🧬 [SYSTEM] ER VITALS OVERRIDE INITIATED...")
    print("------------------------------------------")

    # Roll the d20
    d20 = random.randint(1, 20)
    total = d20 + tech_mod

    print(f"🎲 DICE ROLL: {d20} + (Tech {tech_mod}) = {total}")

    if total >= 15:
        print("✅ SUCCESS: Bio-signatures masked. Security ticker remains stable.")
        return "SUCCESS"
    elif total == 1:
        print("🚨 CRITICAL FAILURE: The system spiked! Hazard Level +2.")
        return "CRIT_FAIL"
    else:
        print("⚠️ FAILURE: Connection flickered. Hazard Level +1.")
        return "FAIL"

# To play, just run:
# er_vitals_override(tech_mod=character['stats']['tech'])

import random

def quick_hazard_check(stat_mod=2):
    roll = random.randint(1, 20)
    total = roll + stat_mod
    print(f"🎲 ROLL: {roll} + {stat_mod} = {total}")
    if total >= 13:
        print("✅ SUCCESS: You held your breath. The smoke passes.")
    else:
        print("🚨 FAIL: You coughed! Security is alerted.")

quick_hazard_check(stat_mod=2) # Change 2 to your actual Reflex mod

def kick_and_drop(reflex_mod=2):
    roll = random.randint(1, 20)
    total = roll + reflex_mod
    print(f"👟 KICK ROLL: {roll} + {reflex_mod} = {total}")
    if total >= 15:
        print("✅ SUCCESS: You burst through the grate like a shadow. Rodriguez is frozen in shock!")
    else:
        print("🚨 FAIL: You got stuck in the frame! You're hanging halfway out of the ceiling!")

kick_and_drop()

def fan_overload(tech_mod=5): # Use your high Tech mod here!
    roll = random.randint(1, 20)
    total = roll + tech_mod
    print(f"⚡ TECH ROLL: {roll} + {tech_mod} = {total}")
    if total >= 12:
        print("✅ SUCCESS: The fan reverses! Thick smoke fills the lab, blinding Rodriguez and the cameras.")
    else:
        print("🚨 FAIL: The board shorts out in your hand. You take 1 point of electrical damage!")

fan_overload()

import random

def shadow_confrontation(stat_mod=5): # Using your high Tech/Auth mod
    roll = random.randint(1, 20)
    total = roll + stat_mod

    print("-" * 30)
    print(f"🕵️ CONFRONTATION ROLL: {roll} + {stat_mod} = {total}")
    print("-" * 30)

    if total >= 14:
        print("✅ SUCCESS: Your voice cuts through the smoke like a scalpel.")
        print("The shadow halts. It acknowledges your authority.")
    else:
        print("🚨 FAIL: The shadow doesn't care about your title.")
        print("It turns toward you, and you hear the whir of a weapon charging.")
    print("-" * 30)

# This line actually RUNS the roll!
shadow_confrontation()

import random

def er_vitals_override(tech_mod=5):
    print("🛰️ [SYSTEM] ER VITALS OVERRIDE INITIATED...")
    print("------------------------------------")

    # Roll the d20
    d20 = random.randint(1, 20)
    total = d20 + tech_mod

    print(f"🎲 DICE ROLL: {d20} + (Tech {tech_mod}) = {total}")

    if total >= 15:
        print("✅ SUCCESS: Bio-signatures masked. Security ticker reset.")
        return "SUCCESS"
    elif d20 == 1:
        print("⚠️ CRITICAL FAILURE: The system spiked! Hazard Level +2.")
        return "CRIT_FAIL"
    else:
        print("❌ FAILURE: Connection flickered. Hazard Level +1.")
        return "FAIL"

# Execute the override
er_vitals_override(tech_mod=character['modifiers']['tech'])

# Dr. Grant uses his Tech skill to scan the Data Junction for life signs
roll_check("tech")

def roll_check(stat_name):
    modifier = character['modifiers'].get(stat_name, 0)
    die_roll = random.randint(1, 20)
    total = die_roll + modifier
    print(f"🎲 ROLL: {die_roll} + {modifier} ({stat_name.upper()})")
    print(f"📊 TOTAL: {total}")
    return total

roll_check("tech")

# The Silent Kill using the Data Spike
# DC is lowered to 10 because of your 'Perfect Tactical Awareness'
result = roll_check("tech")

if result >= 10:
    print("💀 [TERMINAL] UPLOAD COMPLETE: BIO-SENTINEL NEURAL LINK SEVERED.")
    print("The creature slumps, dead before it hit the floor.")
else:
    print("⚠️ [TERMINAL] UPLOAD INTERRUPTED: THE CREATURE IS AWAKE!")

# Initialize inventory if it doesn't exist
if 'inventory' not in character:
    character['inventory'] = ["Data Spike"]

# Consuming the Data Spike
if "Data Spike" in character['inventory']:
    character['inventory'].remove("Data Spike")
    print("Inventory Updated: Data Spike consumed.")
else:
    print("No Data Spike found in inventory.")

# Update your credits from the previous loot find
character['credits'] = 3622
show_dashboard()

# Final Save for the Scene
character['time_tokens'] = 39
character['credits'] = 3622
character['hazard_level'] = 3
print("✅ SESSION DATA SAVED. READY FOR COMMAND TIER.")
show_dashboard()

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Krebsville Nights | Colab Sync Setup</title>
        <link rel="stylesheet" href="styles.css" />
    </head>
    <body class="bg-slate-950" style="overflow-y: auto">
        <div class="max-w-3xl mx-auto px-6 py-10">
            <h1 class="text-3xl font-bold neon-violet mb-2 tracking-widest">
                COLAB SYNC SETUP
            </h1>
            <div
                class="h-1 w-24 bg-gradient-to-r from-violet-600 to-pink-600 rounded mb-6"
            ></div>

            <div
                class="border border-violet-600/50 bg-black/40 p-6 rounded mb-8"
            >
                <h2
                    class="text-sm font-bold uppercase tracking-widest text-pink-400 mb-3"
                >
                    HOW IT WORKS
                </h2>
                <p class="text-slate-300 text-sm leading-relaxed mb-3">
                    Your Google Colab controller talks to the Krebsville game
                    through a sync API. When you run commands in Colab (combat,
                    loot, heal), the game updates in real-time on screen. The
                    browser polls the server every 3 seconds for changes.
                </p>
                <p class="text-slate-300 text-sm leading-relaxed">
                    <strong class="neon-violet">Step 1:</strong> Copy the code
                    below into your Colab notebook.<br />
                    <strong class="neon-violet">Step 2:</strong> Type
                    <span class="text-green-400 font-mono">sync</span> in the
                    game console to start syncing.<br />
                    <strong class="neon-violet">Step 3:</strong> Run Colab
                    functions. The game screen updates automatically.
                </p>
            </div>

            <div
                class="border border-violet-600/50 bg-black/40 p-6 rounded mb-8"
            >
                <div class="flex justify-between items-center mb-3">
                    <h2
                        class="text-sm font-bold uppercase tracking-widest text-pink-400"
                    >
                        COLAB CODE - PASTE INTO YOUR NOTEBOOK
                    </h2>
                    <button
                        onclick="copyCode()"
                        class="action-button text-xs px-3 py-1"
                        id="copy-btn"
                    >
                        COPY
                    </button>
                </div>
                <pre
                    id="colab-code"
                    class="bg-slate-900 border border-slate-700 p-4 rounded text-xs text-green-400 overflow-x-auto whitespace-pre"
                    style="max-height: 500px; overflow-y: auto"
                >import requests
import json
import random

# ========================================
# KREBSVILLE NIGHTS - COLAB SYNC MODULE
# ========================================
# Paste this cell into your Colab notebook.
# It connects your controller to the live game.

KREBSVILLE_URL = "<span id="sync-url" class="text-cyan-300">LOADING...</span>"

# --- SYNC FUNCTIONS ---

def push_state(character):
    """Push your character state to the game server."""
    payload = {
        "source": "colab",
        "state": {
            "name": character.get("name", "Dr. Grant"),
            "time_tokens": character.get("time_tokens", 37),
            "credits": character.get("credits", 3480),
            "hazard_level": character.get("hazard_level", 0),
            "health": character.get("health", 100),
            "companion": character.get("companion", "Nurse Carter"),
            "modifiers": character.get("modifiers", {"tech": 5, "stealth": 3, "reflexes": 2}),
            "currentZoneId": character.get("currentZoneId", 1),
            "inventory": character.get("inventory", []),
            "visitedZones": character.get("visitedZones", [1]),
            "turnCount": character.get("turnCount", 0)
        }
    }
    try:
        r = requests.post(f"{KREBSVILLE_URL}/api/state", json=payload, timeout=10)
        data = r.json()
        print(f"[SYNC] State pushed. Synced at: {data.get('synced', 'unknown')}")
        return data
    except Exception as e:
        print(f"[ERROR] Sync failed: {e}")
        return None

def pull_state():
    """Pull the current game state from the server."""
    try:
        r = requests.get(f"{KREBSVILLE_URL}/api/state", timeout=10)
        data = r.json()
        if data.get("state"):
            print("[SYNC] State pulled from server.")
            return data["state"]
        else:
            print("[SYNC] No state on server yet.")
            return None
    except Exception as e:
        print(f"[ERROR] Pull failed: {e}")
        return None

def run_action(action, params=None):
    """Run a game action on the server and get the result."""
    payload = {
        "source": "colab",
        "action": action,
        "params": params or {}
    }
    try:
        r = requests.post(f"{KREBSVILLE_URL}/api/action", json=payload, timeout=10)
        data = r.json()
        return data
    except Exception as e:
        print(f"[ERROR] Action failed: {e}")
        return None

# --- GAME ACTIONS (match your existing controller) ---

def roll_check(stat_name):
    """Roll a d20 + stat modifier via the server."""
    result = run_action("roll_check", {"stat": stat_name})
    if result:
        print(f"  ROLL: {result['roll']} + {result['modifier']} ({result['stat'].upper()})")
        print(f"  TOTAL: {result['total']}")
    return result

def engage_combat(enemy_name, enemy_difficulty):
    """Run combat through the server. Updates game state."""
    result = run_action("combat", {"enemy": enemy_name, "difficulty": enemy_difficulty})
    if result:
        init = result.get("initiative", {})
        print(f"  COMBAT: {result.get('enemy', enemy_name)}")
        print(f"  INITIATIVE: {init.get('roll', '?')} + mod = {init.get('total', '?')}")
        if "attack" in result:
            atk = result["attack"]
            print(f"  ATTACK: {atk.get('roll', '?')} + mod = {atk.get('total', '?')} vs DC {atk.get('dc', '?')}")
        print(f"  RESULT: {result.get('combatResult', '?').upper()}")
        if result.get("state"):
            print(f"  Tokens: {result['state'].get('time_tokens', '?')} | Credits: {result['state'].get('credits', '?')}")
    return result

def carter_heal():
    """Use companion healing (100 credits = +5 time tokens)."""
    result = run_action("carter_heal")
    if result:
        if result.get("healed"):
            print(f"  Nurse Carter uses a stim-pack. +5 Time Tokens restored.")
        else:
            print(f"  Not enough Credits for medical supplies!")
    return result

def generate_loot(is_elite_vault=False):
    """Search for loot. Elite vaults give double rewards."""
    result = run_action("generate_loot", {"is_elite_vault": is_elite_vault})
    if result:
        print(f"  FOUND: {result.get('credits_found', 0)} Credits")
        print(f"  ITEM: {result.get('item', 'nothing')}")
    return result

def er_vitals_override():
    """Run the ER Vitals Override mini-game."""
    result = run_action("er_vitals_override")
    if result:
        print(f"  DICE ROLL: {result.get('roll', '?')} + (Tech {result.get('modifier', '?')}) = {result.get('total', '?')}")
        res = result.get("result", "FAIL")
        if res == "SUCCESS":
            print(f"  SUCCESS: Bio-signatures masked.")
        elif res == "CRIT_FAIL":
            print(f"  CRITICAL FAILURE: System spiked! Hazard Level increased!")
        else:
            print(f"  FAILURE: Connection flickered. Hazard Level +1.")
    return result

def move_zone(zone_id):
    """Move Dr. Grant to a different zone."""
    result = run_action("move_zone", {"zone_id": zone_id})
    if result:
        if result.get("moved"):
            print(f"  Moved to Zone {zone_id}. (-1 Time Token)")
        else:
            print(f"  Move failed: {result.get('reason', 'unknown')}")
    return result

def show_dashboard(character=None):
    """Show the current game state."""
    state = pull_state() if not character else character
    if state:
        print("=" * 50)
        print(f"  LOCATION: Zone {state.get('currentZoneId', '?')}")
        print(f"  TIME TOKENS: {state.get('time_tokens', '?')} | CREDITS: {state.get('credits', '?')}")
        print(f"  HAZARD LEVEL: {state.get('hazard_level', '?')}/5")
        print(f"  HEALTH: {state.get('health', '?')}/100")
        print(f"  COMPANION: {state.get('companion', 'Nurse Carter')}")
        print("=" * 50)

def get_sync_payload(character=None):
    """Generate a formatted status report."""
    state = pull_state() if not character else character
    if not state:
        print("[ERROR] No state available.")
        return
    status = "HAZARD CRITICAL" if state.get('hazard_level', 0) >= 4 else "STABLE"
    payload = f"""
--- DATA SYNC: DR. GRANT ---
STATUS: {status}
LOCATION: Zone {state.get('currentZoneId', '?')}
------------------------------------------
  TIME TOKENS: {state.get('time_tokens', '?')}
  ARP CREDITS: {state.get('credits', '?')}
  HAZARD LEVEL: {state.get('hazard_level', '?')}
  HEALTH: {state.get('health', '?')}/100
------------------------------------------
--- END SYNC ---
"""
    print(payload)

# --- QUICK TEST ---
print("[KREBSVILLE SYNC] Module loaded.")
print(f"[KREBSVILLE SYNC] Server: {KREBSVILLE_URL}")
print("[KREBSVILLE SYNC] Run push_state(character) to sync your state.")
print("[KREBSVILLE SYNC] Run show_dashboard() to see current state.")</pre>
            </div>

            <div
                class="border border-violet-600/50 bg-black/40 p-6 rounded mb-8"
            >
                <h2
                    class="text-sm font-bold uppercase tracking-widest text-pink-400 mb-3"
                >
                    API ENDPOINTS
                </h2>
                <div class="space-y-3 text-xs font-mono">
                    <div>
                        <span class="text-green-400">GET</span>
                        <span class="text-slate-300">/api/state</span>
                        <p class="text-slate-500 mt-1">
                            Returns the current shared game state
                        </p>
                    </div>
                    <div>
                        <span class="text-yellow-400">POST</span>
                        <span class="text-slate-300">/api/state</span>
                        <p class="text-slate-500 mt-1">
                            Push game state from Colab. Body: { source: "colab",
                            state: {...} }
                        </p>
                    </div>
                    <div>
                        <span class="text-yellow-400">POST</span>
                        <span class="text-slate-300">/api/action</span>
                        <p class="text-slate-500 mt-1">
                            Execute actions: roll_check, combat, carter_heal,
                            generate_loot, er_vitals_override, move_zone
                        </p>
                    </div>
                    <div>
                        <span class="text-green-400">GET</span>
                        <span class="text-slate-300">/api/sync-log</span>
                        <p class="text-slate-500 mt-1">
                            View the sync activity log
                        </p>
                    </div>
                </div>
            </div>

            <div class="text-center">
                <a href="/" class="action-button inline-flex px-6 py-3"
                    >BACK TO GAME</a
                >
            </div>
        </div>

        <script>
            const url = window.location.origin;
            document.getElementById("sync-url").textContent = url;

            const codeEl = document.getElementById("colab-code");
            codeEl.innerHTML = codeEl.innerHTML.replace("LOADING...", url);

            function copyCode() {
                const code = codeEl.innerText;
                navigator.clipboard.writeText(code).then(() => {
                    const btn = document.getElementById("copy-btn");
                    btn.textContent = "COPIED!";
                    btn.classList.add("neon-cyan");
                    setTimeout(() => {
                        btn.textContent = "COPY";
                        btn.classList.remove("neon-cyan");
                    }, 2000);
                });
            }
        </script>
    </body>
</html>

# === KREBSVILLE NIGHTS: SESSION SAVE STATE (7:50 PM) ===
# Paste this to sync your data for the Command Tier

character['time_tokens'] = 39  # +2 Bonus for Silent Kill efficiency
character['credits'] = 3622      # +142 from Lab Scavenge
character['hazard_level'] = 3    # Stabilized after successful Override
inventory = ["Master Encryption Key", "Gene-Drive Data"] # Data Spike consumed

print("💾 SESSION UPDATED: DATA STORED FOR COMMAND TIER")
print("-----------------------------------------------")
show_dashboard()

!pip install supabase

from supabase import create_client

# Get these from your Supabase Project Settings > API
url = "https://jtnebqrvvqpxjpwhlisi.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bmVicXJ2dnFweGpwd2hsaXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMTAzNTEsImV4cCI6MjA4NjY4NjM1MX0.C66r23A4XRDcP_LnqWZ4cKNQM3tt3pY2VwRgNkTC54Y"
supabase = create_client(url, key)

def push_to_cloud():
    data = {
        "time_tokens": character['time_tokens'],
        "credits": character['credits'],
        "hazard_level": character['hazard_level'],
        "inventory": ["Master Encryption Key", "Gene-Drive Data"]
    }
    # Update row 1 (Dr. Grant's save)
    supabase.table("game_sessions").update(data).eq("character_name", "Dr. Grant").execute()
    print("🌐 [CLOUD SYNC] Dr. Grant's vitals uploaded to the grid.")

def log_to_replit(message, msg_type="info"):
    log_entry = {
        "message": message,
        "type": msg_type
    }
    supabase.table("narrative_logs").insert(log_entry).execute()

# EXAMPLE USAGE IN COMBAT:
def engage_combat_live(target, dc):
    result = roll_check("tech")
    if result >= dc:
        msg = f"SUCCESS: Dr. Grant neutralized {target} with a roll of {result}."
        log_to_replit(msg, "combat")
    else:
        msg = f"FAILURE: {target} detected Dr. Grant! Roll: {result}."
        log_to_replit(msg, "critical")

# INITIALIZING SESSION: COMMAND TIER BREACH
character['time_tokens'] = 39
character['credits'] = 3622
character['hazard_level'] = 3

# Push the starting state to the cloud
log_to_replit("SYSTEM BREACH SUCCESSFUL. WELCOME TO COMMAND TIER, DR. GRANT.", "info")
push_to_cloud()

!pip install psycopg2-binary

import psycopg2
import os

# Paste your connection string here
DATABASE_URL = "postgresql://neondb_owner:npg_2Bj4kAELebsG@ep-quiet-king-aiswqwtx-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

def save_to_neon():
    try:
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()

        # This SQL updates Dr. Grant's stats in your Neon branch
        query = """
        UPDATE game_sessions
        SET time_tokens = %s, credits = %s, hazard_level = %s
        WHERE character_name = 'Dr. Grant';
        """
        cur.execute(query, (character['time_tokens'], character['credits'], character['hazard_level']))

        conn.commit()
        cur.close()
        conn.close()
        print("🚀 [NEON SYNC] Progress backed up to the cloud.")
    except Exception as e:
        print(f"❌ Connection failed: {e}")

import requests

def quick_save(checkpoint_name):
    """Creates a database anchor in Neon for recovery."""
    print(f"⚓ [ANCHOR] Creating timeline anchor: {checkpoint_name}...")
    save_to_neon()
    # In a real scenario, this would trigger a Neon Branch via API
    print(f"✅ [SUCCESS] Anchor 'QUICKSAVE_{checkpoint_name}' established.")

def restore_from_quicksave(checkpoint_name):
    global DATABASE_URL
    url = f"https://console.neon.tech/api/v1/projects/{PROJECT_ID}/branches"
    headers = {"Authorization": f"Bearer {NEON_API_KEY}"}

    try:
        response = requests.get(url, headers=headers)
        branches = response.json().get('branches', [])

        target_name = f"QUICKSAVE_{checkpoint_name}"
        branch = next((b for b in branches if b['name'] == target_name), None)

        if branch:
            new_host = f"{branch['id']}.us-east-2.aws.neon.tech"
            DATABASE_URL = DATABASE_URL.replace(DATABASE_URL.split('@')[1].split('/')[0], new_host)
            print(f"⏳ [RECOVERY] Timeline shifted to {target_name}.")
        else:
            print(f"❌ [ERROR] No anchor found with name: {target_name}")
    except Exception as e:
        print(f"❌ [RECOVERY FAILED]: {e}")

# Run this NOW to create your anchor
quick_save("Command_Tier_Entry")

# Final Friday Prep Save
character['time_tokens'] = 39
character['credits'] = 3622
character['hazard_level'] = 3

save_to_neon() # Updates the 'main' timeline
quick_save("Final_Friday_Logoff") # Creates a backup of tonight's end-state

"""### 🛰️ Manus Sync Prompt

Copy and paste this prompt into Manus to synchronize your session:

```text
I am running a Krebsville Nights session in Google Colab. Please sync the following game state to my Neon PostgreSQL database:

- Character: Dr. Grant
- Time Tokens: 39
- Credits: 3622
- Hazard Level: 3
- Inventory: ["Master Encryption Key", "Gene-Drive Data"]

Connection String: postgresql://neondb_owner:npg_2Bj4kAELebsG@ep-quiet-king-aiswqwtx-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require

Action: Update the 'game_sessions' table where character_name is 'Dr. Grant'. If the record doesn't exist, please create it.
```
"""

import sentry_sdk

sentry_sdk.init(
    dsn="https://a36435aba7f6fd7587ecd4bdbd6a9430@o229048.ingest.us.sentry.io/4510892977618944",
    # This captures 100% of transactions—perfect for a solo game session
    traces_sample_rate=1.0,
    # This helps Sentry identify that this error came from Dr. Grant's Brain
    environment="production",
    release="krebsville-nights@1.0.0",
)

import sentry_sdk
from sentry_sdk import add_breadcrumb

sentry_sdk.init(
    dsn="https://a36435aba7f6fd7587ecd4bdbd6a9430@o229048.ingest.us.sentry.io/4510892977618944",
    traces_sample_rate=1.0,
    environment="command-tier-session",
)

def log_game_event(category, message, level="info"):
    """
    Adds a 'Breadcrumb' to Sentry so we can track
    Dr. Grant's actions before a potential crash.
    """
    add_breadcrumb(
        category=category,
        message=message,
        level=level,
    )
    print(f"📡 [SENTRY] Breadcrumb added: {message}")

# --- EXAMPLE USAGE ON FRIDAY ---
# log_game_event("combat", "Engaged Stalker Sentinel", "warning")
# log_game_event("system", "Inserted Master Encryption Key", "info")

"""Zone 0 Reset"""

def reset_ai_to_zone_0():
    system_prompt = """
    CURRENT LOCATION: ZONE 0 (STASIS).
    OBJECTIVE: You are the Krebsville Command System.
    You have no memory of the DOVIC simulation.
    Status is COLD. Await user 'Zone 1' synchronization.
    """
    # This resets the conversation history in your OpenAI call
    game_history = [{"role": "system", "content": system_prompt}]
    print("📡 [ZONE 0] OpenAI Memory Purged. System is Cold.")
    return game_history

# Ensure the character dictionary exists before resetting
try:
    character
except NameError:
    character = {"name": "Dr. Grant", "modifiers": {"tech": 5, "stealth": 3, "reflexes": 2}}

# Resetting for Zone 0
character['time_tokens'] = 50  # Starting fresh with more time!
character['credits'] = 1000     # Standard starting funds
character['hazard_level'] = 0   # No danger yet
character['companion'] = "Nurse Carter"

# Let's update your location too
print("SYSTEM RESET: Dr. Grant has returned to Zone 0 Entry Point.")

# Defining a fallback for show_dashboard if it hasn't been run yet
if 'show_dashboard' in globals():
    show_dashboard()
else:
    print(f"STATUS: {character}")

# 1. Define save_progress if it doesn't exist to prevent NameError
def save_progress():
    import json
    with open('game_save.txt', 'w') as f:
        f.write(str(character))
    print("💾 Progress saved to disk.")

# 2. Add the notes section to the dictionary
character['notes'] = []

# 3. Create a helper function to add notes easily
def add_journal_entry(note_text):
    character['notes'].append(note_text)
    print(f"📓 JOURNAL UPDATED: {note_text}")
    save_progress()

# 4. Try it out
add_journal_entry("Found a strange flickering monitor in Zone 0 Entry.")

# UPDATE CELL 1: CHARACTER + CLOUD CONFIG
character = {
    "name": "Dr. Grant",
    "time_tokens": 50,
    "credits": 1000,
    "hazard_level": 0,
    "companion": "Nurse Carter",
    "inventory": [],
    "modifiers": {"tech": 5, "stealth": 3, "reflexes": 2},
    "notes": ["Arrived at Sector 7 Entry. Systems nominal."]
}

# Add your Cloud Credentials here
CLOUD_CONFIG = {
    "BIN_ID": "69a2d7ddae596e708f521f90",
    "API_KEY": "$2a$10$BBjlg4xK53UVDNmdOlIBFug1aPq9fW/P.QyuMYsI6vKyK1wOkIqnC"

}

def save_progress():
    # 1. Local Save
    with open("game_save.txt", "w") as f:
        f.write(str(character))

    # 2. Cloud Save (Triggering the JSONbin API)
    cloud_save()

    print("💾 LOCAL & ☁️ CLOUD SAVE COMPLETE.")